configd-1061.40.2

diff --git a/src/configd/get-mobility-info b/src/configd/get-mobility-info
--- a/src/configd/get-mobility-info
+++ b/src/configd/get-mobility-info
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (c) 2004-2015 Apple Inc.
+# Copyright (c) 2004-2017 Apple Inc.
 #
 # get-mobility-info
 #
@@ -7,6 +7,30 @@
 #
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
+
+OUTDIR=""
+NO_PCAP=0
+NO_TAR=0
+
+while getopts f:PT OPTION ; do
+	case ${OPTION} in
+		f)
+		   OUTDIR="${OPTARG}"
+		   if [ ! -d "${OUTDIR}" ]; then
+			echo "# ${PROGNAME}: \"${OUTDIR}\" is not a directory"
+			exit 1
+		   fi
+		   ;;
+		P)
+		   NO_PCAP=1
+		   ;;
+		T)
+		   NO_TAR=1
+		   ;;
+		\?)
+		   ;;
+	esac
+done
 
 #
 # Disclaimer
@@ -44,13 +68,19 @@ else
 	TAIL_25000="/bin/cat"
 fi
 
-OUT="mobility-info-`date +'%m.%d.%Y.%H%M%S'`"
-OUTDIR="/var/tmp"
-if [ -d ~/Desktop ]; then
-	OUTDIR=~/Desktop
-elif [ "`readlink /tmp`" = "private/var/tmp" ]; then
-	OUTDIR=/Library/Logs/CrashReporter
-	mkdir -p ${OUTDIR}
+OUT="mobility-info-`date +'%Y.%m.%d.%H%M%S'`"
+
+if [ -z $OUTDIR ]; then
+	OUTDIR="/var/tmp"
+	if [ -d ~/Desktop ]; then
+		OUTDIR=~/Desktop
+	elif [ "`readlink /tmp`" = "private/var/tmp" ]; then
+		OUTDIR=/Library/Logs/DiagnosticReports
+		if [ ! -d /Library/Logs/DiagnosticReports -a -d /Library/Logs/CrashReporter ]; then
+			OUTDIR=/Library/Logs/CrashReporter
+		fi
+		mkdir -p ${OUTDIR}
+	fi
 fi
 
 umask 077
@@ -61,18 +91,20 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-GZ_EXT=""
-GZ_OPT=""
-if [ -x /usr/bin/gzip ]; then
-	GZ_EXT=".gz"
-	GZ_OPT="-z"
-fi
+if [ $NO_TAR -eq 0 ]; then
+	GZ_EXT=""
+	GZ_OPT=""
+	if [ -x /usr/bin/gzip ]; then
+		GZ_EXT=".gz"
+		GZ_OPT="-z"
+	fi
 
-ARCHIVE=`mktemp -q "${OUTDIR}/${OUT}.tar${GZ_EXT}"`
-if [ $? -ne 0 ]; then
-	echo "Could not create snapshot archive"
-	rm -rf "${WORKDIR}"
-	exit 1
+	ARCHIVE=`mktemp -q "${OUTDIR}/${OUT}.tar${GZ_EXT}"`
+	if [ $? -ne 0 ]; then
+		echo "Could not create snapshot archive"
+		rm -rf "${WORKDIR}"
+		exit 1
+	fi
 fi
 
 cd "${WORKDIR}"
@@ -82,39 +114,35 @@ echo "Please wait, collecting information and statistics"
 echo ""
 
 #
-# Execute network reachability/DNS commands early
+# collect packet capture with kernel ring buffer if available
 #
-echo "#"						>  reachability-info
-echo '# scutil -d -v -r www.apple.com "" no-server'	>> reachability-info
-echo "#"						>> reachability-info
-scutil -d -v -r www.apple.com "" no-server		>> reachability-info	2>&1
+stop_pcap () {
+	#
+	# Stop the packet capture
+	#
+	if [ ${PCAP_STARTED} -ne 0 ]; then
+		trap '' SIGINT
+		/usr/local/bin/netdiagnose stop packetcapture			2>&1
+		PCAP_STARTED=0
+	fi
+}
 
-echo "#"						>> reachability-info
-echo '# scutil -d -v -r 0.0.0.0 no-server'		>> reachability-info
-echo "#"						>> reachability-info
-scutil -d -v -r 0.0.0.0          no-server		>> reachability-info	2>&1
-
-if [ -x /usr/bin/dig -a -f /etc/resolv.conf ]; then
-	/usr/bin/dig -t any -c any www.apple.com	> dig-results		2>/dev/null
+PCAP_STARTED=0
+if [ -x /usr/local/bin/netdiagnose -a ${NO_PCAP} -ne 1 ]; then
+	trap stop_pcap SIGINT
+	/usr/local/bin/netdiagnose -p "${WORKDIR}" start packetcapture		2>&1
+	PCAP_STARTED=1
 fi
 
 #
-# Signal "networkd" and "mDNSResponder" early to log their "state" info. This
-# logging will continue while we execute a few other commands and should be
-# complete by the time we collect the log content.
+# get-network-info
 #
-if [ -x /usr/bin/killall ]; then
-	#
-	# request networkd state
-	#
-	${PRIV} /usr/bin/killall -INFO networkd					2>/dev/null
-
-	#
-	# request mDNSResponder state
-	#
-	${PRIV} /usr/bin/killall -INFO mDNSResponder				2>/dev/null
-
-	sleep 1
+if [ -x /System/Library/Frameworks/SystemConfiguration.framework/Resources/get-network-info ]; then
+	/bin/sh /System/Library/Frameworks/SystemConfiguration.framework/Resources/get-network-info -s -c -P "${WORKDIR}"
+elif [ -x /System/Library/Frameworks/SystemConfiguration.framework/get-network-info ]; then
+	/bin/sh /System/Library/Frameworks/SystemConfiguration.framework/get-network-info -s -c -P "${WORKDIR}"
+elif [ -x /System/Library/PrivateFrameworks/SystemConfiguration.framework/get-network-info ]; then
+	/bin/sh /System/Library/PrivateFrameworks/SystemConfiguration.framework/get-network-info -s -c -P "${WORKDIR}"
 fi
 
 #
@@ -122,37 +150,6 @@ fi
 #
 if [ -x /bin/ps ]; then
 	/bin/ps axlww					> ps			2>&1
-fi
-
-#
-# network interface configuration
-#
-if [ -x /sbin/ifconfig ]; then
-	/sbin/ifconfig -a -L -b -m -r -v -v		> ifconfig		2>&1
-	if [ $? -ne 0 ]; then
-		/sbin/ifconfig -a			> ifconfig		2>&1
-	fi
-fi
-
-#
-# network route configuration
-#
-if [ -x /usr/sbin/netstat ]; then
-	/usr/sbin/netstat -n -r -a -l			> netstat		2>&1
-fi
-
-#
-# DHCP configuration
-#
-if [ -x /sbin/ifconfig ]; then
-	for if in `/sbin/ifconfig -l`
-	do
-		case ${if} in
-		lo* )	;;
-		en* )	ipconfig getpacket ${if}	> ipconfig-${if}	2>&1
-			;;
-		esac
-	done
 fi
 
 #
@@ -206,13 +203,6 @@ if [ -x /usr/bin/pmset ]; then
 fi
 
 #
-# Host name
-#
-if [ -x /bin/hostname ]; then
-	/bin/hostname					> hostname		2>&1
-fi
-
-#
 # Host configuration
 #
 if [ -x /usr/bin/hostinfo ]; then
@@ -223,58 +213,14 @@ if [ -e /etc/hostconfig ]; then
 fi
 
 #
-# DNS configuration
-#
-scutil --dns						> dns-configuration	2>&1
-if [ -e /etc/resolv.conf ]; then
-	cat /etc/resolv.conf				> etc.resolv.conf	2>&1
-fi
-if [ -e /var/run/resolv.conf ]; then
-	cat /var/run/resolv.conf			> var.run.resolv.conf	2>&1
-fi
-if [ -e /etc/resolver ]; then
-	tar -c -H /etc/resolver				> etc.resolver.tar	2>/dev/null
-fi
-
-#
-# Proxy configuration
-#
-scutil -d -v --proxy					> proxy-configuration	2>&1
-
-#
-# Network information
-#
-if [ -x /sbin/ifconfig ]; then
-	echo "#"					>  network-information
-	echo "# scutil --nwi"				>> network-information
-	echo "#"					>> network-information
-	scutil --nwi					>> network-information	2>&1
-	for if in `/sbin/ifconfig -l`
-	do
-		echo ""					>> network-information
-		echo "#"				>> network-information
-		echo "# scutil --nwi ${if}"		>> network-information
-		echo "#"				>> network-information
-		scutil --nwi ${if}			>> network-information	2>&1
-	done
-fi
-
-#
 # System / network preferences
 #
 for f in										\
-	/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist		\
 	/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist	\
 	/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist	\
-	/Library/Preferences/SystemConfiguration/com.apple.nat.plist			\
-	/Library/Preferences/SystemConfiguration/com.apple.smb.server.plist		\
 	/Library/Preferences/SystemConfiguration/com.apple.wifi.plist			\
-	/Library/Preferences/SystemConfiguration/preferences.plist			\
 	/Library/Preferences/com.apple.alf.plist					\
 	/Library/Preferences/com.apple.sharing.firewall.plist				\
-	/Library/Preferences/com.apple.networkextension.plist				\
-	/Library/Preferences/com.apple.networkextension.control.plist			\
-	/Library/Preferences/com.apple.networkextension.necp.plist			\
 	/Library/Preferences/com.apple.wwand.plist					\
 
 do
@@ -285,9 +231,16 @@ do
 done
 
 #
+# Install log
+#
+if [ -e /var/log/install.log ]; then
+	cat /var/log/install.log			> install.log		2>&1
+fi
+
+#
 # System / network preferences (from other volumes)
 #
-/bin/ls /Volumes 2>/dev/null								\
+mount -t hfs | grep "/Volumes/" | sed -e 's:^.* on /Volumes/::' -e 's: ([^(]*$::'	\
 | while read volume
 do
 	V_PATH="/Volumes/${volume}"
@@ -295,6 +248,7 @@ do
 		# if the path is a symlink
 		continue
 	fi
+
 	for f in									\
 		/Library/Preferences/SystemConfiguration/Networkinterfaces.plist	\
 		/Library/Preferences/SystemConfiguration/preferences.plist		\
@@ -320,26 +274,6 @@ elif [ -e /Library/Preferences/SystemConfiguration/bootpd.plist ]; then
 fi
 
 #
-# configd's cache
-#
-${PRIV} scutil -p --snapshot
-if [ -f /var/tmp/configd-store.plist ]; then
-	cat /var/tmp/configd-store.plist		> configd-store.plist	2>&1
-fi
-if [ -f /var/tmp/configd-pattern.plist ]; then
-	cat /var/tmp/configd-pattern.plist		> configd-pattern.plist	2>&1
-fi
-if [ -f /var/tmp/configd-session.plist ]; then
-	cat /var/tmp/configd-session.plist		> configd-session.plist	2>&1
-fi
-if [ -f /var/tmp/configd-state ]; then
-	cat /var/tmp/configd-state			> configd-state		2>&1
-fi
-if [ -f /var/tmp/configd-reachability ]; then
-	cat /var/tmp/configd-reachability		> configd-reachability	2>&1
-fi
-
-#
 # mounted filesystems
 #
 mount							> mounted-filesystems	2>&1
@@ -351,107 +285,6 @@ ${PRIV} cat /etc/hosts 					> etc.hosts		2>/dev/null
 #
 if   [ -x /usr/sbin/kextstat ]; then
 	/usr/sbin/kextstat				> kextstat		2>&1
-fi
-
-#
-# network statistics
-#
-/bin/echo -n ""							>  network-statistics
-
-if   [ -x /usr/sbin/arp ]; then
-	echo "#"						>> network-statistics
-	echo "# arp -n -a"					>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/arp -n -a					>> network-statistics	2>&1
-fi
-
-if [ -x /usr/sbin/netstat ]; then
-	echo "#"						>> network-statistics
-	echo "# netstat -A -a -l -n"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -A -a -l -n				>> network-statistics	2>&1
-
-	echo "#"						>> network-statistics
-	echo "# netstat -s"					>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -s					>> network-statistics	2>&1
-
-	echo "#"						>> network-statistics
-	echo "# netstat -mmm"					>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -mmm					>> network-statistics	2>&1
-
-	echo "#"						>> network-statistics
-	echo "# netstat -i -n -d"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -i -n -d				>> network-statistics	2>&1
-
-	echo "#"						>> network-statistics
-	echo "# netstat -g -n -s"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -g -n -s				>> network-statistics	2>&1
-
-	echo "#"						>> network-statistics
-	echo "# netstat -i -x R"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -i -x R				>> network-statistics	2>&1
-	echo "#"						>> network-statistics
-
-	echo "# netstat -a -n -p mptcp"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -a -n -p mptcp			>> network-statistics	2>/dev/null
-
-	echo "#"						>> network-statistics
-	echo "# netstat -s -p mptcp"				>> network-statistics
-	echo "#"						>> network-statistics
-	/usr/sbin/netstat -s -p mptcp				>> network-statistics	2>/dev/null
-
-	if [ -x /sbin/ifconfig ]; then
-		for if in `/sbin/ifconfig -l`
-		do
-			`/sbin/ifconfig -v ${if} | grep -q TXSTART`
-			if [ $? -eq 0 ]; then
-				echo "#"			>> network-statistics
-				echo "# netstat -qq -I ${if}"	>> network-statistics
-				echo "#"			>> network-statistics
-				/usr/sbin/netstat -qq -I ${if}	>> network-statistics	2>&1
-			fi
-			`/sbin/ifconfig -v ${if} | grep -q RXPOLL`
-			if [ $? -eq 0 ]; then
-				echo "#"			>> network-statistics
-				echo "# netstat -Q -I ${if}"	>> network-statistics
-				echo "#" 			>> network-statistics
-				/usr/sbin/netstat -Q -I ${if}	>> network-statistics   2>&1
-			fi
-		done
-	fi
-fi
-
-if [ -x /usr/sbin/ndp ]; then
-	echo "#"					>> network-statistics
-	echo "# ndp -n -a"				>> network-statistics
-	echo "#"					>> network-statistics
-	/usr/sbin/ndp -n -a				>> network-statistics	2>&1
-
-	echo "#"					>> network-statistics
-	echo "# ndp -n -p"				>> network-statistics
-	echo "#"					>> network-statistics
-	/usr/sbin/ndp -n -p				>> network-statistics	2>&1
-
-	echo "#"					>> network-statistics
-	echo "# ndp -n -r"				>> network-statistics
-	echo "#"					>> network-statistics
-	/usr/sbin/ndp -n -r				>> network-statistics	2>&1
-
-	if [ -x /sbin/ifconfig ]; then
-		for if in `/sbin/ifconfig -l`
-		do
-			echo "#"			>> network-statistics
-			echo "# ndp -i ${if}"		>> network-statistics
-			echo "#"			>> network-statistics
-			/usr/sbin/ndp -i ${if}		>> network-statistics	2>&1
-		done
-	fi
 fi
 
 if [ -x /sbin/pfctl ]; then
@@ -485,7 +318,30 @@ fi
 # open files
 #
 if [ -x /usr/sbin/lsof ]; then
-	${PRIV} /usr/sbin/lsof -n -P -T q		> lsof			2>&1
+	${PRIV} /usr/sbin/lsof +c 0 -n -O -P -T q	> lsof			2>&1	&
+	LSOF_PID=$!
+	# Init a watchdog for lsof
+	(
+		WAIT_TIME=5
+		while [ $WAIT_TIME -gt 0 ]
+		do
+			${PRIV} kill -0 ${LSOF_PID}	2>/dev/null
+			if [ $? -eq 0 ]; then
+				sleep 1
+				# lsof is gathering data..
+				WAIT_TIME=$((WAIT_TIME-1))
+				continue
+			fi
+
+			# lsof completed gathering data
+			break
+		done
+
+		if [ $WAIT_TIME -eq 0 ]; then
+			# lsof timed out
+			${PRIV} kill ${LSOF_PID}	2>/dev/null
+		fi
+	) &
 fi
 
 #
@@ -495,7 +351,7 @@ if [ -x /usr/local/bin/ddt ]; then
     /bin/echo -n ""					>  dispatch-info
     for BIN in		\
 	configd		\
-	mDNSResponder	\
+	discoveryd	\
 
     do
 	echo "#"					>> dispatch-info
@@ -513,49 +369,6 @@ if [ -x /usr/bin/odutil ]; then
 	echo "# odutil show all"			>> od-info
 	echo "#"					>> od-info
 	${PRIV} /usr/bin/odutil show all		>> od-info		2>&1
-fi
-
-#
-# IPsec configuration
-#
-if [ -x /usr/sbin/setkey -a -x /usr/bin/perl ]; then
-	echo "#"						>  ipsec
-	echo "# setkey -D"					>> ipsec
-	echo "#"						>> ipsec
-	${PRIV} /usr/sbin/setkey -D				\
-	| /usr/bin/perl -M'Digest::MD5 qw(md5_hex)' -l -n -e '
-		if (/^(\s+[AE]:\s+\S+\s+)"?(.*)"?\s*$/) {
-			printf "%s[MD5:%s]%s\n", $1, md5_hex($2 . "\n"), $3;
-		} else {
-			printf "%s\n", $_;
-		}
-	'							>> ipsec
-
-	echo ""							>> ipsec
-	echo "#"						>> ipsec
-	echo "# setkey -Pp -D"					>> ipsec
-	echo "#"						>> ipsec
-	${PRIV} /usr/sbin/setkey -Pp -D				>> ipsec
-
-	for CF in /var/run/racoon/*.conf
-	do
-		if [ ! -r "${CF}" ]; then
-			continue
-		fi
-
-		echo ""						>> ipsec
-		echo "#"					>> ipsec
-		echo "# ${CF}"					>> ipsec
-		echo "#"					>> ipsec
-		${PRIV} cat ${CF}				\
-		| /usr/bin/perl -M'Digest::MD5 qw(md5_hex)' -l -n -e '
-			if (/^(\s+shared_secret\s+use\s+)"?([^\s;"]+)"?(.*)/) {
-				printf "%s[MD5:%s]%s\n", $1, md5_hex($2 . "\n"), $3;
-			} else {
-				printf "%s\n", $_;
-			}
-		'						>> ipsec
-	done
 fi
 
 #
@@ -632,7 +445,7 @@ if [ -x /usr/sbin/lsof -a -x /bin/ls ]; then
 		N=`expr ${N} + 1`
 
 		echo "#"						>> system-statistics
-		${PRIV} /usr/sbin/lsof -- ${lock}			>> system-statistics	2>&1
+		${PRIV} /usr/sbin/lsof +c 0 -- ${lock}			>> system-statistics	2>&1
 	done
 fi
 
@@ -660,14 +473,15 @@ report_binary_info()
 get_binary_info()
 {
     for BIN in										\
-	/usr/libexec/InternetSharing							\
 	/usr/libexec/bootpd								\
 	/usr/libexec/configd								\
-	/usr/libexec/misd								\
+	/usr/libexec/discoveryd								\
 	/usr/sbin/awacsd								\
 	/usr/sbin/mDNSResponder								\
 	/usr/sbin/pppd									\
 	/usr/sbin/racoon								\
+	/usr/libexec/misd								\
+	/usr/libexec/InternetSharing							\
 	/System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration	\
 
     do
@@ -775,53 +589,22 @@ if [ -x /usr/bin/what -a -x /usr/bin/sum -a -x /bin/ls ]; then
 fi
 
 #
-# to give a chance for "networkd" and "mDNSResponder" to finish dumping their
-# state, the last thing we do is collect the logs
+# collect the logarchive
 #
-
-#
-# system log, kernel.log, early boot log messages
-#
-if [ -x /usr/bin/syslog ]; then
-	#
-	# save the recent activity
-	#
-	${PRIV} /usr/bin/syslog -T local.3					\
-		| ${TAIL_25000}							> syslog
-
-	#
-	# save just the "kernel" activity (in case some of the
-	# interesting/relevant message are before the messages
-	# captured above.
-	#
-	${PRIV} /usr/bin/syslog -T local.3 -k Facility kern			\
-		| ${TAIL_25000}							> kernel
-
-	if [ -d /var/log/DiagnosticMessages ]; then
-		# save any MessageTracer activity
-		${PRIV} /usr/bin/syslog	-d /var/log/DiagnosticMessages		\
-					-F raw					\
-					-T local.3				\
-			| ${TAIL_25000}						> DiagnosticMessages
-	fi
-else
-	if [ -f /var/log/system.log ]; then
-		${PRIV} ${TAIL_25000} /var/log/system.log			> system.log
-	fi
-	if [ -f /var/log/kernel.log ]; then
-		${PRIV} ${TAIL_25000} /var/log/kernel.log			> kernel.log
+if [ -x /usr/bin/log ]; then
+	LOGARCHIVE_START_TIME=`date -v -1d +"%Y-%m-%d %H:%M:%S"`
+	LOGARCHIVE_OUTPUT="system_logs.logarchive"
+	${PRIV} /usr/bin/log collect --livedata --output "${LOGARCHIVE_OUTPUT}" --start "${LOGARCHIVE_START_TIME}"	2>/dev/null
+	if [ -d ${LOGARCHIVE_OUTPUT} ]; then
+		${PRIV} chown -R ${UID} "${LOGARCHIVE_OUTPUT}"
 	fi
 fi
+
+#
+# dmesg
+#
 if [ -x /sbin/dmesg ]; then
 	${PRIV} /sbin/dmesg							> dmesg
-fi
-
-#
-# IPConfiguration log
-#
-if [ -f /var/log/com.apple.IPConfiguration.bootp ]; then
-	${PRIV} ${TAIL_2000} /var/log/com.apple.IPConfiguration.bootp	\
-							> com.apple.IPConfiguration.bootp
 fi
 
 #
@@ -851,13 +634,6 @@ do
 	fi
 done
 
-#
-# application firewall log
-#
-if [ -f /var/log/appfirewall.log ]; then
-	${PRIV} ${TAIL_2000} /var/log/appfirewall.log	> appfirewall.log
-fi
-
 if [ -x /bin/ls ]; then
 	#
 	# collect crash reports
@@ -869,6 +645,8 @@ if [ -x /bin/ls ]; then
 			awacsd			\
 			bootpd			\
 			configd			\
+			discoveryd		\
+			discoveryd_helper	\
 			eapolclient		\
 			mDNSResponder		\
 			mDNSResponderHelper	\
@@ -891,19 +669,6 @@ if [ -x /bin/ls ]; then
 			fi
 		done
 	done
-
-	#
-	# collect any verbose logging output
-	#
-	/bin/ls -1	/Library/Logs/CrashReporter/com.apple.networking.*.log*		\
-			2>/dev/null							\
-	| while read log
-	do
-		if [ -f "${log}" ]; then
-			b="`basename ${log}`"
-			${PRIV} cat "${log}"			> "${b}"		2>&1
-		fi
-	done
 fi
 
 #
@@ -914,19 +679,41 @@ if [ -x /usr/local/bin/crstackshot ]; then
 fi
 
 #
-# collect everything into a single archive
+# wait for background activity (eg: lsof)
 #
-cd "${WORKDIR}/.."
-tar -c ${GZ_OPT} -f "${ARCHIVE}" "${OUT}"
-rm -rf "${WORKDIR}"
+wait
 
-if [ ${UID} -eq 0 ]; then
-	if [ -n "${SUDO_UID}" -a -n "${SUDO_GID}" ]; then
-		if [ ${UID} -ne ${SUDO_UID} ]; then
-			chown ${SUDO_UID}:${SUDO_GID} "${ARCHIVE}"
+#
+# Stop the packet capture
+#
+stop_pcap
+
+if [ $NO_TAR -eq 0 ]; then
+	#
+	# collect everything into a single archive
+	#
+	cd "${WORKDIR}/.."
+	tar -c ${GZ_OPT} -f "${ARCHIVE}" "${OUT}"
+	rm -rf "${WORKDIR}"
+
+	if [ ${UID} -eq 0 ]; then
+		if [ -n "${SUDO_UID}" -a -n "${SUDO_GID}" ]; then
+			if [ ${UID} -ne ${SUDO_UID} ]; then
+				chown ${SUDO_UID}:${SUDO_GID} "${ARCHIVE}"
+			fi
 		fi
 	fi
+
+	echo "Network data collected to \"${ARCHIVE}\""
+else
+	mv "${WORKDIR}" "${OUTDIR}"
+
+	if [ ${UID} -eq 0 ]; then
+		if [ -n "${SUDO_UID}" -a -n "${SUDO_GID}" ]; then
+			if [ ${UID} -ne ${SUDO_UID} ]; then
+				chown -R ${SUDO_UID}:${SUDO_GID} "${OUTDIR}/${OUT}"
+			fi
+		fi
+	fi
+	echo "Network data collected to \"${OUTDIR}/${OUT}\""
 fi
-
-echo "Network data collected to \"${ARCHIVE}\""
-
