Add sandboxed home directory
Signed-off-by: kamil <kamillys@gmail.com>

diff --git a/src/dyld/darling b/src/dyld/darling
--- a/src/dyld/darling
+++ b/src/dyld/darling
@@ -50,52 +50,64 @@ check_prefix() {
 
 setup_prefix() {
     prefix_pkg="/tmp/prefix.$$.pkg"
+    DPREFIX=$1
 
-    >&2 echo "Setting up prefix at $1"
-    >&2 echo 
+    # Check argument
+    if [ -z "${DPREFIX}" ]; then
+        >&2 echo "ERROR: missing prefix location"
+        return 1
+    fi
 
-    mkdir -p "$1"
-    rm -f "$1/darling-prefix"
+    mkdir -p "${DPREFIX}"
+    rm -f "${DPREFIX}/darling-prefix"
 
-    rm -f "$1/system-root"
-    ln -s / "$1/system-root"
+    rm -f "${DPREFIX}/system-root"
+    ln -s / "${DPREFIX}/system-root"
 
-    rm -f "$1/darling-prefix"
-    ln -s "system-root${DARLING_PREFIX}" "$1/darling-prefix"
+    rm -f "${DPREFIX}/darling-prefix"
+    ln -s "system-root${DARLING_PREFIX}" "${DPREFIX}/darling-prefix"
 
-    rm -f "$1/dev"
-    ln -sf "system-root/dev" "$1/dev"
+    rm -f "${DPREFIX}/dev"
+    ln -sf "system-root/dev" "${DPREFIX}/dev"
 
-    rm -f "$1/home"
-    ln -sf "system-root/home" "$1/home"
+    rm -rf "${DPREFIX}/sandboxed-home"
+    rm -f "${DPREFIX}/home"
+    if [ "${DARLING_SANDBOXED_HOME}" != "1" ]; then
+        >&2 echo "Setting sandboxed home"
+        mkdir "${DPREFIX}/sandboxed-home"
+        ln -sf "sandboxed-home" "${DPREFIX}/home"
+        find /home/ -mindepth 1 -maxdepth 1 -type d -exec mkdir ${DPREFIX}/"{}" \;
+    else
+        ln -sf "system-root/home" "${DPREFIX}/home"
+    fi
 
-    rm -f "$1/Users"
-    ln -sf "home" "$1/Users"
+    rm -f "${DPREFIX}/Users"
+    ln -sf "home" "${DPREFIX}/Users"
 
-    rm -f "$1/tmp"
-    ln -sf "system-root/tmp" "$1/tmp"
+    rm -f "${DPREFIX}/tmp"
+    ln -sf "system-root/tmp" "${DPREFIX}/tmp"
 
-    rm -f "$1/etc" 2>/dev/null || true
-    mkdir -p "$1/etc"
-    ln -sf "../system-root/etc/timezone" "$1/etc/timezone"
-    ln -sf "../system-root/etc/resolv.conf" "$1/etc/resolv.conf"
-    ln -sf "../system-root/etc/passwd" "$1/etc/passwd"
-    ln -sf "../system-root/etc/group" "$1/etc/group"
-    ln -sf "../system-root/etc/hosts" "$1/etc/hosts"
-    ln -sf "../system-root/etc/localtime" "$1/etc/localtime" || true
+    rm -f "${DPREFIX}/etc" 2>/dev/null || true
+    mkdir -p "${DPREFIX}/etc"
+    ln -sf "../system-root/etc/timezone" "${DPREFIX}/etc/timezone"
+    ln -sf "../system-root/etc/resolv.conf" "${DPREFIX}/etc/resolv.conf"
+    ln -sf "../system-root/etc/passwd" "${DPREFIX}/etc/passwd"
+    ln -sf "../system-root/etc/group" "${DPREFIX}/etc/group"
+    ln -sf "../system-root/etc/hosts" "${DPREFIX}/etc/hosts"
+    ln -sf "../system-root/etc/localtime" "${DPREFIX}/etc/localtime" || true
     
-    mkdir -p "$1/usr/share"
-	rm -f "$1/usr/share/zoneinfo" 2>/dev/null || true
-    ln -sf "../../system-root/usr/share/zoneinfo" "$1/usr/share/zoneinfo"
+    mkdir -p "${DPREFIX}/usr/share"
+	rm -f "${DPREFIX}/usr/share/zoneinfo" 2>/dev/null || true
+    ln -sf "../../system-root/usr/share/zoneinfo" "${DPREFIX}/usr/share/zoneinfo"
 
-    mkdir -p "$1/Volumes" "$1/Applications" "$1/var/root" || true
-    mkdir -p "$1/var/run" || true
-    ln -sf "../../system-root/dev/log" "$1/var/run/syslog" || true
+    mkdir -p "${DPREFIX}/Volumes" "${DPREFIX}/Applications" "${DPREFIX}/var/root" || true
+    mkdir -p "${DPREFIX}/var/run" || true
+    ln -sf "../../system-root/dev/log" "${DPREFIX}/var/run/syslog" || true
 
     # Clean up old cruft (symlinks)
-    rm -f "$1/bin" "$1/usr/bin" "$1/etc" "$1/System/Library/Frameworks" "$1/System/Library/PrivateFrameworks" 2>/dev/null || true
-    cp -rf "${DARLING_PREFIX}/libexec/darling/"* "$1"
-    echo -n "$selfmtime" > "$1/.update-timestamp"
+    rm -f "${DPREFIX}/bin" "${DPREFIX}/usr/bin" "${DPREFIX}/etc" "${DPREFIX}/System/Library/Frameworks" "${DPREFIX}/System/Library/PrivateFrameworks" 2>/dev/null || true
+    cp -rf "${DARLING_PREFIX}/libexec/darling/." "${DPREFIX}"
+    echo -n "$selfmtime" > "${DPREFIX}/.update-timestamp"
 
     install_pkg "org.darlinghq.pkg.OpenSSLCertificates"
 
@@ -170,6 +182,12 @@ darling_unload() {
     fi
 }
 
+darling_clean_home() {
+    if $(darling_check); then
+        rm "$DPREFIX/.update-timestamp" 2>&1 > /dev/null || true
+    fi
+}
+
 if [ $# -eq 0 ]; then
     >&2 echo "This is Darling, a runtime environment for OS X applications."
     >&2 echo
@@ -182,6 +200,9 @@ if [ $# -eq 0 ]; then
     #>&2 echo -e "\tdarling pkgutil\t\t\tInstall PKG packages"
     >&2 echo -e "\tdarling load\t\t\tLoad kernel module"
     >&2 echo -e "\tdarling unload\t\t\tUnload kernel module"
+    >&2 echo -e "\tdarling clean-home\t\t\tMarks darling home directory to rebuilt"
+    >&2 echo
+    >&2 echo "Export DARLING_SANDBOXED_HOME=1 to have sandboxed /home in Darling root"
     >&2 echo
     >&2 echo "The prefix is specified by the DPREFIX environment variable."
     >&2 echo "The default DPREFIX is \$HOME/.darling"
@@ -225,6 +246,9 @@ case "$1" in
     ;;
 "unload")
     darling_unload
+    ;;
+"clean-home")
+    darling_clean_home
     ;;
 *)
     check_prefix
